language: java

jdk: oraclejdk8
env:
  global: ORG_GRADLE_PROJECT_downloadIdeaSources=false
  matrix:
        - ORG_GRADLE_PROJECT_ideaVersion=LATEST-EAP-SNAPSHOT RUST_VERSION=nightly
        - ORG_GRADLE_PROJECT_ideaVersion=2016.1              RUST_VERSION=1.13.0

before_script:
  # We want to use the nightly toolchain because we want to check
  # if some new syntax breaks our parser.
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain $RUST_VERSION -y
  - export PATH=$HOME/.cargo/bin:$PATH
  - cargo install rustfmt

# https://docs.travis-ci.com/user/languages/java/#Caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
