branches:
  only:
    - staging
    - master
    - trying

language: java

jdk: openjdk8

env:
  global:
    - OLD_RUST_VERSION=1.32.0
    - CURRENT_RUST_VERSION=1.41.0
    - NIGHLY_RUST_VERSION=nightly-2019-12-19
    - RUST_SRC_WITH_SYMLINK=$HOME/.rust-src

matrix:
  include:
    # 201 platform
    - name: idea-201/old-rust
      env: RUST_VERSION=$OLD_RUST_VERSION ORG_GRADLE_PROJECT_platformVersion=201 ORG_GRADLE_PROJECT_ideaVersion=IU-2020.1 ORG_GRADLE_PROJECT_clionVersion=CL-2020.1 ORG_GRADLE_PROJECT_nativeDebugPluginVersion=201.6668.113 ORG_GRADLE_PROJECT_graziePluginVersion=2020.1
    - name: idea-201/stable-rust
      env: RUST_VERSION=$CURRENT_RUST_VERSION ORG_GRADLE_PROJECT_platformVersion=201
    - name: clion-201/stable-rust
      env: RUST_VERSION=$CURRENT_RUST_VERSION ORG_GRADLE_PROJECT_platformVersion=201 ORG_GRADLE_PROJECT_baseIDE=clion
    - name: idea-202/nightly-rust
      env: RUST_VERSION=$NIGHLY_RUST_VERSION ORG_GRADLE_PROJECT_platformVersion=202
    - name: clion-202/nightly-rust
      env: RUST_VERSION=$NIGHLY_RUST_VERSION ORG_GRADLE_PROJECT_platformVersion=202 ORG_GRADLE_PROJECT_baseIDE=clion

install: true

before_script:
  - dig +short myip.opendns.com @resolver1.opendns.com || true
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain $RUST_VERSION -y
  - export PATH=$HOME/.cargo/bin:$PATH
  - rustup component add rust-src
  - rustup component add clippy
  - rustup component add rustfmt
  - if [ ! $RUST_VERSION \< "1.40.0" ]; then cargo install evcxr_repl; fi # BACKCOMPAT: Rust 1.39.0
  - ln -s $(rustc --print sysroot)/lib/rustlib/src/rust/src $RUST_SRC_WITH_SYMLINK
  - ./check-license.sh
  - ./gradlew :resolveDependencies -Pkotlin.incremental=false --no-daemon
  - ./gradlew assemble testClasses -Pkotlin.incremental=false --no-daemon

script:
  - travis_wait 30 ./gradlew check -PexcludeTests=org/rustPerformanceTests/** -Pkotlin.incremental=false --no-daemon
  - ./gradlew runPrettyPrintersTests --no-daemon
