branches:
  except:
    - staging.tmp

language: java

jdk: oraclejdk8
env:
  matrix:
        # https://youtrack.jetbrains.com/issue/IDEA-173171
        # - ORG_GRADLE_PROJECT_ideaVersion=LATEST-EAP-SNAPSHOT RUST_VERSION=nightly
        - ORG_GRADLE_PROJECT_ideaVersion=2017.1              RUST_VERSION=1.18.0

before_script:
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain $RUST_VERSION -y
  - export PATH=$HOME/.cargo/bin:$PATH
  - rustfmt --help || cargo install rustfmt --force

install: true

script:
  # BACKCOMPAT:
  # HACK: Force grammar kit to use current IDEA version when generating parser.
  # For actual compilation and running the version from the matrix will be used.
  - ORG_GRADLE_PROJECT_ideaVersion=2017.1 ./gradlew generateRustParser generateTomlParser
  - ./gradlew check -x generateRustParser -x generateTomlParser

# https://docs.travis-ci.com/user/languages/java/#Caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.cargo/registry/
    - $HOME/.cargo/bin/
