branches:
  only:
    - staging
    - master
    - trying

language: java

jdk: openjdk8

env:
  global:
    - OLD_RUST_VERSION=1.28.0
    - CURRENT_RUST_VERSION=1.39.0
    - NIGHLY_RUST_VERSION=nightly-2019-12-05
    - RUST_SRC_WITH_SYMLINK=$HOME/.rust-src

matrix:
  include:
    # 192 platform
    - name: idea-192/old-rust
      env: RUST_VERSION=$OLD_RUST_VERSION ORG_GRADLE_PROJECT_platformVersion=192 ORG_GRADLE_PROJECT_ideaVersion=IU-2019.2.1 ORG_GRADLE_PROJECT_clionVersion=CL-2019.2.1
    - name: idea-192/stable-rust
      env: RUST_VERSION=$CURRENT_RUST_VERSION ORG_GRADLE_PROJECT_platformVersion=192
    - name: clion-192/stable-rust
      env: RUST_VERSION=$CURRENT_RUST_VERSION ORG_GRADLE_PROJECT_platformVersion=192 ORG_GRADLE_PROJECT_baseIDE=clion
    # 193 platform
    - name: idea-193/nightly-rust
      env: RUST_VERSION=$NIGHLY_RUST_VERSION ORG_GRADLE_PROJECT_platformVersion=193
    - name: clion-193/nightly-rust
      env: RUST_VERSION=$NIGHLY_RUST_VERSION ORG_GRADLE_PROJECT_platformVersion=193 ORG_GRADLE_PROJECT_baseIDE=clion

install: true

before_script:
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain $RUST_VERSION -y
  - export PATH=$HOME/.cargo/bin:$PATH
  - rustup component add rust-src
  - if [ $RUST_VERSION != $OLD_RUST_VERSION ]; then rustup component add clippy-preview; fi # BACKCOMPAT: Rust 1.28.0
  - rustup component add rustfmt-preview
  - ln -s $(rustc --print sysroot)/lib/rustlib/src/rust/src $RUST_SRC_WITH_SYMLINK
  - ./check-license.sh
  - ./gradlew :resolveDependencies -Pkotlin.incremental=false --no-daemon
  - ./gradlew assemble testClasses -Pkotlin.incremental=false --no-daemon

script:
  - travis_wait 30 ./gradlew check -PexcludeTests=org/rustPerformanceTests/** -Pkotlin.incremental=false --no-daemon
  - ./gradlew runPrettyPrintersTests --no-daemon
