environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - curl -sSf -o rustup-init.exe https://dev-static.rust-lang.org/rustup/dist/i686-pc-windows-gnu/rustup-init.exe
  - rustup-init.exe -y
  - set PATH=C:\Users\appveyor\.cargo\bin;%PATH%
  - cargo install rustfmt

build_script:
  - gradlew.bat assemble testClasses --no-daemon

test_script:
  - gradlew.bat check --no-daemon

cache:
  - C:\Users\appveyor\.cargo

# Appveyor does not allow huge cache folders
# https://www.appveyor.com/docs/build-cache/
# - C:\Users\appveyor\.gradle
