branches:
  only:
    - staging
    - trying

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  RUST_VERSION: 1.41.0
  JAVA_OPTS: -Xmx2g
  RUST_SRC_WITH_SYMLINK: C:\Users\appveyor\.rust-src

install:
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs -FileName rustup-init.exe
  - rustup-init.exe --default-toolchain %RUST_VERSION% -y
  - set PATH=C:\Users\appveyor\.cargo\bin;%PATH%
  - rustup component add rust-src
  - rustup component add clippy-preview
  - rustup component add rustfmt-preview
  - for /f "delims=*" %%a in ('rustc --print sysroot') do (Mklink /D "C:\Users\appveyor\.rust-src" "%%a\lib\rustlib\src\rust\src\")

build_script:
  - gradlew.bat -Dkotlin.compiler.execution.strategy="in-process" assemble testClasses --no-daemon

test_script:
  - gradlew.bat check -PexcludeTests=org/rustPerformanceTests/** --no-daemon
