[package]
name = "rustc_feature"
version = "0.1.0"
edition = "2021"

[dependencies]
rustc_span = { path = "../rustc_span" }
rustc_data_structures = { path = "../rustc_data_structures" }

[build-dependencies]
reqwest = { version = "0.11.10", features = ["blocking"] }
