test_dir = "./tests"
pretty_printers_path = "./../prettyPrinters/"
print_stdout = true
native_rust = false
lldb_batchmode = "./lldb_batchmode.py"
lldb_lookup = "lldb_lookup"
python = "python"
gdb_lookup = "gdb_lookup"
