pretty_printers_path = "./../prettyPrinters/"
print_stdout = true

[lldb]
# Note, `python` property is intentionally missing here. See `runPrettyPrintersTests` gradle task
lldb_batchmode = "./lldb_batchmode.py"
