name: auto updates

on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * 1' # try each Monday

jobs:
    update-nightly:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  token: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}

            - name: Prepare for updates
              uses: ./.github/actions/preparations-for-updates

            - name: Update nightly
              run: python scripts/update_nightly.py --token ${{ secrets.WORKFLOW_GITHUB_TOKEN }}

    update-stable:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  token: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}

            - name: Prepare for updates
              uses: ./.github/actions/preparations-for-updates
              with:
                  toolchain: stable

            - name: Update stable
              run: python scripts/update_stable.py --token ${{ secrets.WORKFLOW_GITHUB_TOKEN }}

    update-compiler-features:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  token: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}

            - name: Prepare for updates
              uses: ./.github/actions/preparations-for-updates

            - name: Update compiler features
              run: python scripts/update_compiler_features.py --token ${{ secrets.WORKFLOW_GITHUB_TOKEN }}

    update-lints:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  token: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}

            - name: Prepare for updates
              uses: ./.github/actions/preparations-for-updates

            - name: Update lints
              run: python scripts/update_lints.py --token ${{ secrets.WORKFLOW_GITHUB_TOKEN }}


    update-evcxr-repl:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  token: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}

            - name: Prepare for updates
              uses: ./.github/actions/preparations-for-updates

            - name: Update evcxr_repl
              run: python scripts/update_repl.py --token ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
