name: build native code

on:
    workflow_call:
        inputs:
            rust-version:
                required: true
                type: string
            cache:
                required: true
                type: boolean

jobs:
    build-native-code:
        strategy:
            fail-fast: true
            matrix:
                config:
                    - name: linux
                      arch: x86-64
                      os: ubuntu-18.04
                      target: x86_64-unknown-linux-gnu
                      artifact_path: native-helper/target/x86_64-unknown-linux-gnu/release/intellij-rust-native-helper
                    - name: windows
                      arch: x86-64
                      os: windows-latest
                      target: x86_64-pc-windows-msvc
                      artifact_path: native-helper/target/x86_64-pc-windows-msvc/release/intellij-rust-native-helper.exe
                    - name: macos
                      arch: x86-64
                      os: macos-latest
                      target: x86_64-apple-darwin
                      artifact_path: native-helper/target/x86_64-apple-darwin/release/intellij-rust-native-helper
                    - name: macos
                      arch: arm64
                      os: macos-11
                      target: aarch64-apple-darwin
                      artifact_path: native-helper/target/aarch64-apple-darwin/release/intellij-rust-native-helper

        name: ${{ matrix.config.name }}-${{ matrix.config.arch }}
        runs-on: ${{ matrix.config.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Cache native code artifact
              id: cache-native-code-artifact
              if: inputs.cache
              uses: actions/cache@v2.1.4
              with:
                  path: ${{ matrix.config.artifact_path }}
                  key: ${{ matrix.config.arch }}-${{ runner.os }}-native-helper-${{ inputs.rust-version }}-${{ hashFiles('native-helper/src/**', 'native-helper/Cargo.toml', 'native-helper/Cargo.lock') }}

            - name: Set up Rust
              if: ${{ !inputs.cache || !steps.cache-native-code-artifact.outputs.cache-hit }}
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: ${{ inputs.rust-version }}
                  target: ${{ matrix.config.target }}
                  default: true

            - name: Build
              if: ${{ !inputs.cache || !steps.cache-native-code-artifact.outputs.cache-hit }}
              uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: --manifest-path native-helper/Cargo.toml --target ${{ matrix.config.target }} --release

            - name: Publish
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ matrix.config.name }}-${{ matrix.config.arch }}
                  path: ${{ matrix.config.artifact_path }}
