name: build native code

on:
    workflow_call:
        inputs:
            rust-version:
                required: true
                type: string
            cache:
                required: true
                type: boolean

env:
    CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc

jobs:
    build-native-code:
        strategy:
            fail-fast: true
            matrix:
                config:
                    - name: linux
                      arch: x86-64
                      os: ubuntu-latest
                      container: ubuntu:18.04
                      target: x86_64-unknown-linux-gnu
                      artifact_path: native-helper/target/x86_64-unknown-linux-gnu/release/intellij-rust-native-helper
                    - name: linux
                      arch: arm64
                      os: ubuntu-latest
                      container: ubuntu:18.04
                      target: aarch64-unknown-linux-gnu
                      artifact_path: native-helper/target/aarch64-unknown-linux-gnu/release/intellij-rust-native-helper
                    - name: windows
                      arch: x86-64
                      os: windows-latest
                      target: x86_64-pc-windows-msvc
                      artifact_path: native-helper/target/x86_64-pc-windows-msvc/release/intellij-rust-native-helper.exe
                    - name: windows
                      arch: arm64
                      os: windows-latest
                      target: aarch64-pc-windows-msvc
                      artifact_path: native-helper/target/aarch64-pc-windows-msvc/release/intellij-rust-native-helper.exe
                    - name: macos
                      arch: x86-64
                      os: macos-latest
                      target: x86_64-apple-darwin
                      artifact_path: native-helper/target/x86_64-apple-darwin/release/intellij-rust-native-helper
                    - name: macos
                      arch: arm64
                      os: macos-11
                      target: aarch64-apple-darwin
                      artifact_path: native-helper/target/aarch64-apple-darwin/release/intellij-rust-native-helper

        name: ${{ matrix.config.name }}-${{ matrix.config.arch }}
        runs-on: ${{ matrix.config.os }}
        container: ${{ matrix.config.container }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Cache native code artifact
              id: cache-native-code-artifact
              if: inputs.cache
              uses: actions/cache@v3
              with:
                  path: ${{ matrix.config.artifact_path }}
                  key: ${{ matrix.config.arch }}-${{ matrix.config.os }}-native-helper-${{ inputs.rust-version }}-${{ hashFiles('native-helper/src/**', 'native-helper/Cargo.toml', 'native-helper/Cargo.lock') }}

            # Since we use pure ubuntu container, it doesn't contain `curl` and `rustup`.
            # So let's install them manually
            - name: Install Rust toolchain dependencies
              if: ${{ matrix.config.container == 'ubuntu:18.04' && (!inputs.cache || !steps.cache-native-code-artifact.outputs.cache-hit) }}
              shell: bash
              run: |
                  apt-get update && apt-get install -y build-essential curl
                  curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL "https://sh.rustup.rs" | sh -s -- --profile minimal --default-toolchain none -y
                  echo "${CARGO_HOME:-$HOME/.cargo}/bin" >> $GITHUB_PATH

            - name: Set up Rust
              if: ${{ !inputs.cache || !steps.cache-native-code-artifact.outputs.cache-hit }}
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: ${{ inputs.rust-version }}
                  target: ${{ matrix.config.target }}
                  default: true

            - name: Install Linux arm64 linker
              if: matrix.config.target == 'aarch64-unknown-linux-gnu'
              run: |
                apt-get update
                apt-get -y install gcc-aarch64-linux-gnu

            - name: Build
              if: ${{ !inputs.cache || !steps.cache-native-code-artifact.outputs.cache-hit }}
              uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: --manifest-path native-helper/Cargo.toml --target ${{ matrix.config.target }} --release

            - name: Publish
              uses: actions/upload-artifact@v3
              with:
                  name: ${{ matrix.config.name }}-${{ matrix.config.arch }}
                  path: ${{ matrix.config.artifact_path }}
