name: check

on:
    push:
        branches:
            - master
            - staging
            - trying
    pull_request:

jobs:
    check-license:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Check license
              run: ./check-license.sh

    build:
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest, windows-latest ]
                rust-version: [ 1.45.0, nightly-2020-07-10]
                base-ide: [ idea, clion ]
                platform-version: [ 201, 202 ]
                include:
                    - os: ubuntu-latest
                      # Don't forget to update condition in `Set up additional env variables` step
                      rust-version: 1.32.0
                      base-ide: idea
                      platform-version: 201

        runs-on: ${{ matrix.os }}
        env:
            ORG_GRADLE_PROJECT_baseIDE: ${{ matrix.base-ide }}
            ORG_GRADLE_PROJECT_platformVersion: ${{ matrix.platform-version }}

        steps:
            - uses: actions/checkout@v1

            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                  java-version: 1.8

            - name: Set up Rust
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: ${{ matrix.rust-version }}
                  components: rust-src, rustfmt, clippy
                  default: true

            - name: Set up Rust nightly
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: nightly

            - name: Install evcxr
              if: matrix.os != 'windows-latest' && matrix.rust-version >= '1.40.0' # BACKCOMPAT: Rust 1.39.0
              uses: actions-rs/cargo@v1
              with:
                  command: install
                  args: evcxr_repl

            - name: Install grcov
              uses: actions-rs/cargo@v1
              with:
                  command: install
                  toolchain: nightly
                  args: grcov

            - name: Check environment
              run: |
                  rustc --version
                  rustup component list --installed
                  cargo install --list

            - name: Set up additional env variables
              if: matrix.rust-version == '1.32.0'
              # see https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
              run: |
                  echo "::set-env name=ORG_GRADLE_PROJECT_ideaVersion::IU-2020.1"
                  echo "::set-env name=ORG_GRADLE_PROJECT_clionVersion::CL-2020.1"
                  echo "::set-env name=ORG_GRADLE_PROJECT_nativeDebugPluginVersion::201.6668.113"
                  echo "::set-env name=ORG_GRADLE_PROJECT_graziePluginVersion::2020.1"

            - name: Set up test env variables
              run: echo "::set-env name=RUST_SRC_WITH_SYMLINK::$HOME/.rust-src"

            - name: Create symlink for Rust stdlib Unix
              if: matrix.os != 'windows-latest'
              run: ln -s $(rustc --print sysroot)/lib/rustlib/src/rust/src $RUST_SRC_WITH_SYMLINK

            - name: Create symlink for Rust stdlib Windows
              if: matrix.os == 'windows-latest'
              run: New-Item -ItemType Junction -Path "$env:RUST_SRC_WITH_SYMLINK" -Target "$(rustc --print sysroot)/lib/rustlib/src/rust/src"

            - name: Download
              uses: eskatos/gradle-command-action@v1
              with:
                  arguments: :resolveDependencies -Pkotlin.incremental=false --no-daemon

            - name: Build
              uses: eskatos/gradle-command-action@v1
              with:
                  arguments: assemble testClasses -Pkotlin.incremental=false --no-daemon

            - name: Check
              uses: eskatos/gradle-command-action@v1
              with:
                  arguments: check -PexcludeTests=org/rustPerformanceTests/** -Pkotlin.incremental=false --no-daemon

            - name: Check bundled Rust formatters
              if: matrix.os != 'windows-latest'
              uses: eskatos/gradle-command-action@v1
              with:
                  arguments: runPrettyPrintersTests --no-daemon
