name: check

on:
    push:
        branches:
            - master
            - staging
            - trying
    pull_request:
    # Trigger workflow every day to create/update caches for other builds
    # See https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache
    # to get more details about cache access
    schedule:
        -   cron: '0 3 * * *'

# Allow cancelling all previous runs for the same branch
# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    calculate-git-info:
        runs-on: ubuntu-18.04
        outputs:
            is_bors_branch: ${{ steps.calculate-git-info.outputs.is_bors_branch }}
            is_master_branch: ${{ steps.calculate-git-info.outputs.is_master_branch }}
            checked: ${{ steps.calculate-git-info.outputs.checked }}
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Set up Python
              uses: actions/setup-python@v1
              with:
                  python-version: 3.7

            - name: Calculate git info
              id: calculate-git-info
              run: |
                  echo "::set-output name=is_bors_branch::${{ github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/trying' }}"
                  echo "::set-output name=is_master_branch::${{ github.ref == 'refs/heads/master'}}"
                  echo "::set-output name=checked::$(python scripts/has_successful_status.py --token ${{ github.token }} --ref ${{ github.sha }} --check_name check)"

            - name: Check git info
              run: |
                  echo "is_bors_branch: ${{ steps.calculate-git-info.outputs.is_bors_branch }}"
                  echo "is_master_branch: ${{ steps.calculate-git-info.outputs.is_master_branch }}"
                  echo "checked: ${{ steps.calculate-git-info.outputs.checked }}"

    build-native-code:
        needs: [ calculate-git-info ]
        # `fromJSON` is used here to convert string output to boolean
        # We always want to trigger all workflow jobs on `schedule` event because it creates/updates caches for other builds.
        # See https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache
        # to get more details about cache access
        if: ${{ github.event_name == 'schedule' || !fromJSON(needs.calculate-git-info.outputs.is_master_branch) || !fromJSON(needs.calculate-git-info.outputs.checked) }}
        strategy:
            fail-fast: true
            matrix:
                rust-version: [ 1.56.1 ]
                config:
                    - name: linux
                      arch: x86-64
                      os: ubuntu-latest
                      target: x86_64-unknown-linux-gnu
                      artifact_path: native-helper/target/x86_64-unknown-linux-gnu/release/intellij-rust-native-helper

        name: ${{ matrix.config.name }}-${{ matrix.config.arch }}
        runs-on: ${{ matrix.config.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Cache native code artifact
              id: cache-native-code-artifact
              uses: actions/cache@v2.1.4
              with:
                  path: ${{ matrix.config.artifact_path }}
                  key: ${{ matrix.config.arch }}-${{ runner.os }}-native-helper-${{ matrix.rust-version }}-${{ hashFiles('native-helper/src/**', 'native-helper/Cargo.toml', 'native-helper/Cargo.lock') }}

            - name: Set up Rust
              if: ${{ !steps.cache-native-code-artifact.outputs.cache-hit }}
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: ${{ matrix.rust-version }}
                  target: ${{ matrix.config.target }}
                  default: true

            - name: Build
              if: ${{ !steps.cache-native-code-artifact.outputs.cache-hit }}
              uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: --manifest-path native-helper/Cargo.toml --target ${{ matrix.config.target }} --release

            - name: Publish
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ matrix.config.name }}-${{ matrix.config.arch }}
                  path: ${{ matrix.config.artifact_path }}

    check-plugin:
        needs: [ calculate-git-info, build-native-code ]
        strategy:
            # `fromJSON` is used here to convert string output to boolean
            fail-fast: ${{ fromJSON(needs.calculate-git-info.outputs.is_bors_branch) }}
            matrix:
                os: [ windows-2022 ]
                wsl-distribution: [ Ubuntu-18.04 ]
                rust-version: [ 1.56.1 ]
                base-ide: [ idea ]
                platform-version: [ 213 ]
                verify-plugin: [ false ]

        runs-on: ${{ matrix.os }}
        timeout-minutes: 120
        env:
            ORG_GRADLE_PROJECT_baseIDE: ${{ matrix.base-ide }}
            ORG_GRADLE_PROJECT_platformVersion: ${{ matrix.platform-version }}
            ORG_GRADLE_PROJECT_compileNativeCode: false

        steps:
            - uses: actions/checkout@v2

            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                  java-version: 11

            - name: Set up WSL
              uses: Vampire/setup-wsl@v1
              with:
                  distribution: ${{ matrix.wsl-distribution }}
                  additional-packages: curl

#            - name: Set up WSL 2
#              run: |
#                  C:\hostedtoolcache\windows\Ubuntu\18.4.0\x64\ubuntu1804.exe config --default-user test

            - name: Set up WSL Rust
              shell: wsl-bash {0}
              run: |
                  curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain none
                  rustup toolchain install nightly --allow-downgrade --profile minimal

            - name: Check environment
              shell: wsl-bash {0}
              run: |
                  rustc --version
                  cargo install --list

            - name: Set up WSL env variables
              shell: pwsh
              run: echo "CI_WSL_DISTRO=${{ matrix.wsl-distribution }}" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

            - name: Load linux binaries
              uses: actions/download-artifact@v2
              with:
                  name: linux-x86-64
                  path: bin/linux/x86-64

            - name: Download
              uses: gradle/gradle-build-action@v1
              with:
                  arguments: ":resolveDependencies -Pkotlin.incremental=false --no-daemon"

            - name: Build
              uses: gradle/gradle-build-action@v1
              with:
                  arguments: "assemble testClasses -Pkotlin.incremental=false --no-daemon"

            - name: Check
              uses: gradle/gradle-build-action@v1
              with:
                  arguments: "check -PexcludeTests=org/rustPerformanceTests/** --continue -Pkotlin.incremental=false --no-daemon"

            - name: Collect fail reports
              if: failure()
              uses: actions/upload-artifact@v2
              with:
                  name: tests-report-${{ matrix.os }}-${{ matrix.rust-version }}-${{ matrix.base-ide }}-${{ matrix.platform-version }}
                  path: |
                      build/reports/tests
                      */build/reports/tests

            - name: Verify plugin
              if: matrix.verify-plugin
              uses: gradle/gradle-build-action@v1
              with:
                  arguments: ":plugin:verifyPlugin"

            - name: Check bundled Rust formatters
              uses: gradle/gradle-build-action@v1
              with:
                  arguments: "runPrettyPrintersTests --no-daemon"

    check:
        needs: [ check-plugin ]
        runs-on: ubuntu-18.04
        steps:
            - name: Finish check
              run: echo "Check finished successfully!"
