name: release branch

on:
    workflow_dispatch:
    schedule:
        - cron: '0 1 * * *' # try everyday

jobs:
    make-release-branch:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ secrets.WORKFLOW_GITHUB_TOKEN }}

            - name: Set up Python
              uses: actions/setup-python@v1
              with:
                  python-version: 3.7

            - name: Set up git user
              run: |
                  git config --local user.email "intellij.rust@gmail.com"
                  git config --local user.name "intellij-rust-bot"

            - name: Check date
              if: github.event_name == 'schedule'
              id: check-date
              run: echo "::set-output name=result::$(python scripts/check_release_branch_date.py)"

            - name: Make release branch
              if: github.event_name != 'schedule' || fromJSON(steps.check-date.outputs.result).create_release_branch
              run: python scripts/make_release_branch.py

            - name: Create new milestone
              if: github.event_name != 'schedule' || fromJSON(steps.check-date.outputs.result).create_release_branch
              run: python scripts/make_next_milestone.py --token ${{ secrets.WORKFLOW_GITHUB_TOKEN }}
